In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [ ]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [ ]:
#creating zeroes elemnt 2d matrix
arr0=np.zeros((3,3))
print(arr0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating a own define matrix
arrn=np.full((3,3),10)
print(arrn)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
#identity matrix(dignonal 1)
arrDig=np.eye((3))
print(arrDig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Creating a Matrix with a Valied range
arrRange=np.arange(1,10)
print(arrRange)

AttributeError: module 'numpy' has no attribute 'range'

In [ ]:
#convert 2D->1D
arr2D=np.array([[1,2,3],[4,5,6]])
arr1D=arr2D.flatten()
print(arr1D)

[1 2 3 4 5 6]


In [ ]:
arrLine=np.linspace(1,100,3)
print(arrLine)

[  1.   50.5 100. ]


In [ ]:
#Reshape of array
xarray=np.array([[1,2,3],[4,5,6]])

print(xarray,xarray.shape)

rearray=xarray.reshape(3,2)
print(rearray,rearray.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [ ]:
import numpy as np

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [ ]:
#vectorization
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr**2)
print(arr+arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [ ]:
#Brodcasting
arr=np.array([1,2,3,4,5])
print(arr+5)

[ 6  7  8  9 10]


In [ ]:
import numpy as np
arr=np.array([[1,2],[3,4]])
#mean value
print(arr.mean())
#standard deviation
print(arr.std())


2.5
1.118033988749895


In [ ]:
#Vector Normalization
arr=np.array([[1,2],[3,4]])
mean_val=np.mean(arr)
std_val=np.std(arr)
normalized_arr=(arr-mean_val)/std_val
print(normalized_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [ ]:
#agreagate Function
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Sum of arra:",arr.sum())
print("Max is ",arr.max())
print("min is ",arr.min())
print("mean is ",arr.mean())
print("std is ",arr.std())
print("Product is ",arr.prod())

Sum of arra: 45
Max is  9
min is  1
mean is  5.0
std is  2.581988897471611
Product is  362880


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
#power function
arr=np.array([[1,2],[3,4]])
print(np.square(arr))
print(np.sqrt(arr))

[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
#Logarithm Function
arr=np.array([[1,2],[3,4]])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
#